name: misc

on:
  push:
    branches:
      - 'misc'

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          sudo ./misc.sh

  docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          ./misc.sh

  netnsdocker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --privileged
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          set -x
          ip netns add misc && ip netns exec misc ./misc.sh

  netns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          set -x
          echo "====================="
          ip netns add foo || echo "no foo for you, only misc"
          ip netns list
          echo "====================="
          sudo ip netns add misc && sudo ip netns exec misc ./misc.sh

  unshare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          set -x
          unshare -mrun ./misc.sh

  dockerunshare:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          set -x
          unshare -mrun ./misc.sh
