name: misc

on:
  push:
    branches:
      - 'misc'

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          sudo ./misc.sh

  docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          ./misc.sh
