name: misc

on:
  push:
    branches:
      - 'misc'

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          sudo ./misc.sh

  docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          ./misc.sh

  netnsdocker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/troglobit/misc
      options: --cap-add=NET_ADMIN
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          ip netns add misc
          ip netns list
          ip netns exec misc ./misc.sh
          ip netns exec ip -br link
          ip netns exec ip -br addr

  netns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misc
        run: |
          set -x
          export MISC=$(pwd)/misc.sh
          sudo ip netns add misc
          sudo ip netns list
          sudo ip netns exec misc $MISC
          sudo ip netns exec ip -br link
          sudo ip netns exec ip -br addr
